name: documentation

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: sagemath/sagemath:latest
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y \
            tzdata make texlive texlive-latex-extra \
            texlive-luatex latexmk fonts-freefont-otf \
            xindy python3-sphinx

          sage -pip install sphinx-book-theme
          sage --pip install .

      - name: Build docs
        run: |
          cd docs
          make html
          make latexpdf

      - name: Prepare Pages folder
        run: |
          rm -rf docs/_site
          mkdir -p docs/_site
          touch docs/_build/html/.nojekyll
          cp -r docs/_build/html/* docs/_site/
          cp docs/_build/latex/quivertools.pdf docs/_site/

      - name: Commit built docs
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

          git add docs/_site
          git diff --staged --quiet || git commit -m "Update documentation"
          git push