name: documentation

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: sagemath/sagemath:latest
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y \
            tzdata \
            make \
            texlive \
            texlive-latex-extra \
            texlive-luatex \
            latexmk \
            fonts-freefont-otf \
            xindy \
            python3-sphinx

          sage --pip install sphinx-book-theme
          cd /tmp/build && rm -rf .git
          sage --pip install .

      - name: Build docs
        run: |
          cd docs
          sage -sh -c "make html"
          sage -sh -c "make latexpdf"

      - name: Prepare Pages folder
        run: |
          rm -rf docs/_site
          mkdir -p docs/_site
          touch docs/_build/html/.nojekyll
          
          cp -r docs/_build/html/* docs/_site/
          
          mkdir -p docs/_site/pdf
          cp docs/_build/latex/*.pdf docs/_site/pdf/

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_site

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
